# Generated by Django 4.1.6 on 2023-03-20 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EntrenamientoApp', '0002_rename_instrumento_equipamiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipamiento',
            old_name='imagenInstrumento',
            new_name='imagenEquipamiento',
        ),
    ]
