# Generated by Django 4.1.6 on 2023-03-27 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EntrenamientoApp', '0003_rename_imageninstrumento_equipamiento_imagenequipamiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipamiento',
            old_name='estado',
            new_name='usado',
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('fechaComentario', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='EntrenamientoApp.equipamiento')),
            ],
            options={
                'ordering': ['-fechaComentario'],
            },
        ),
    ]
